---
# ------
# Symlink targets of files in `./root`.a
# ------
links:
  # nushell
  - source: 'root/.config/nushell'
    targets:
      Windows_NT: '{{APPDATA}}\nushell'
      Linux: '{{HOME}}/.config/nushell'
      Darwin: '{{HOME}}/.config/nushell'
  # WezTerm
  - source: 'root/.config/wezterm'
    targets:
      Windows_NT: '{{USERPROFILE}}\.config\wezterm'
      Linux: '{{HOME}}/.config/wezterm'
      Darwin: '{{HOME}}/.config/wezterm'
  # Taskfile
  - source: 'root/Taskfile.yaml'
    targets:
      Windows_NT: '{{USERPROFILE}}\Taskfile.yaml'
      Linux: '{{HOME}}/Taskfile.yaml'
      Darwin: '{{HOME}}/Taskfile.yaml'
  # uv
  - source: 'root/.config/uv'
    targets:
      Windows_NT: '{{USERPROFILE}}\.config\uv'
      Linux: '{{HOME}}/.config/uv'
      Darwin: '{{HOME}}/.config/uv'
  # alacritty
  - source: 'root/.config/alacritty'
    targets:
      Windows_NT: '{{APPDATA}}\alacritty'
      Linux: '{{HOME}}/.config/alacritty'
      Darwin: '{{HOME}}/.config/alacritty'
  # Biome
  - source: 'root/biome.jsonc'
    targets:
      Windows_NT: '{{USERPROFILE}}\biome.jsonc'
      Linux: '{{HOME}}/biome.jsonc'
      Darwin: '{{HOME}}/biome.jsonc'
  # harper-ls
  - source: 'root/.harper-dict.txt'
    targets:
      Windows_NT: '{{USERPROFILE}}\.harper-dict.txt'
      Linux: '{{HOME}}/.harper-dict.txt'
      Darwin: '{{HOME}}/.harper-dict.txt'
  # Starship
  - source: 'root/.config/starship.toml'
    targets:
      Windows_NT: '{{USERPROFILE}}\.config\starship.toml'
      Linux: '{{HOME}}/.config/starship.toml'
      Darwin: '{{HOME}}/.config/starship.toml'
  # Zsh
  - source: 'root/.zshenv'
    targets:
      Linux: '{{HOME}}/.zshenv'
      Darwin: '{{HOME}}/.zshenv'
  - source: 'root/.zshrc'
    targets:
      Linux: '{{HOME}}/.zshrc'
      Darwin: '{{HOME}}/.zshrc'
  - source: 'root/.config/sheldon'
    targets:
      Linux: '{{HOME}}/.config/sheldon'
      Darwin: '{{HOME}}/.config/sheldon'
  # NeoVim
  - source: 'root/.config/nvim'
    targets:
      Windows_NT: '{{USERPROFILE}}\AppData\Local\nvim'
      Linux: '{{HOME}}/.config/nvim'
      Darwin: '{{HOME}}/.config/nvim'
  # GitTui
  - source: 'root/.config/gitui'
    targets:
      # TODO: Configure for Windows
      Linux: '{{HOME}}/.config/gitui'
      Darwin: '{{HOME}}/.config/gitui'
  # Zed
  - source: 'root/.config/zed'
    targets:
      Windows_NT: '{{APPDATA}}\Zed'
      Darwin: '{{HOME}}/.config/zed'
uv-tools:
  - 'esbonio@1.0.0'
  - 'ty@0.0.1a25'
  - 'ruff@0.14.6'
bun-tools:
  - '@anthropic-ai/claude-code@2.1.14'
